# Generated by Django 2.2.14 on 2020-07-02 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='binary',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='boolean',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='char',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
